#!/usr/bin/env python3
"""Adds/updates the same-event check in automation/n8n/AIFeed_Autopilot.json (the n8n fallback).

The shared code is copied from automation/actions/lib/sameevent.js (everything above
"// ---- end of shared same-event code ----"), so the fallback and GitHub Actions run the same
check. Idempotent: run it again after editing that file. test/n8n-fallback.test.js fails if the
JSON drifts from the library.

Flow: Pick Slot Story (prompt) -> Claude Same-Event Check -> Same-Event Verify (classify; one item
per repeat verdict that needs the single-pair confirm) -> Claude Same-Event Confirm (per item) ->
Drop Same-Event Repeats (finalize) -> Fetch Articles.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WF = os.path.join(ROOT, 'n8n', 'AIFeed_Autopilot.json')
SRC = open(os.path.join(ROOT, 'actions', 'lib', 'sameevent.js')).read()
LIB = SRC[:SRC.index('// ---- end of shared same-event code ----')].rstrip() + '\n'
HDR = '// Same-event check (generated by automation/n8n/sync_same_event.py from automation/actions/lib/sameevent.js).\n'
BEGIN, END = '// SAME-EVENT LIB\n', '// END SAME-EVENT LIB\n'
EMPTY = "Reply with exactly: []"

d = json.load(open(WF))
nodes = {n['name']: n for n in d['nodes']}
conn = d['connections']

def strip_lib(code):
    if BEGIN in code:
        code = code[:code.index(BEGIN)] + code[code.index(END) + len(END):]
    return code

def with_lib(code):
    return BEGIN + HDR + LIB + END + strip_lib(code)

# Pick Slot Story: build the prompt with the shared library.
pk = nodes['Pick Slot Story']['parameters']
pc = strip_lib(pk['jsCode'])
tail = "const sameEventPrompt = buildSameEventPrompt(pool, base.postedCompact);\nreturn [{ json: { pool, history, sameEventPrompt } }];"
if 'const posted = base.postedCompact.map(' in pc:
    pc = pc[:pc.index('const posted = base.postedCompact.map(')] + tail
assert pc.rstrip().endswith(tail), 'Pick Slot Story tail not recognised'
pk['jsCode'] = with_lib(pc)

verify = r"""// Classifies the first verdict. A repeat is accepted only if its matched posted item exists and shares a key
// entity; otherwise one item per candidate goes to "Claude Same-Event Confirm" with just that pair.
const { pool } = $('Pick Slot Story').first().json;
const compact = $('Fetch RSS + Dedup').first().json.postedCompact;
const txt = $input.first().json?.content?.[0]?.text || '';
const classified = classifySameEvent(pool, compact, txt); // unreadable -> throws (nothing posted)
const out = classified.filter(r => r.status === 'confirm').map(r => ({ json: { key: r.i, prompt: r.prompt, classified } }));
return out.length ? out : [{ json: { key: null, prompt: '""" + EMPTY + r"""', classified } }];"""

drop = r"""// Applies the verdicts + pair confirms: drops repeats, keeps the first 5 non-repeats as the candidates.
// Fails safe (no post) if a verdict is unreadable or every candidate is a repeat.
const { pool, history } = $('Pick Slot Story').first().json;
const prep = $('Same-Event Verify').all();
const res = $input.all();
const classified = prep[0].json.classified;
const confirmTexts = {};
prep.forEach((p, i) => {
  if (p.json.key !== null && p.json.key !== undefined) confirmTexts[p.json.key] = res[i]?.json?.content?.[0]?.text || '';
});
const r = finalizeSameEvent(pool, classified, confirmTexts);
return [{ json: { candidates: r.candidates, history, sameEventSkipped: r.sameEventSkipped, sameEventOverturned: r.sameEventOverturned } }];"""

def code_node(name, code, pos, nid):
    return {'parameters': {'jsCode': code}, 'id': nid, 'name': name, 'type': 'n8n-nodes-base.code', 'typeVersion': 2, 'position': pos}

def put(node):
    if node['name'] in nodes:
        old = nodes[node['name']]
        old['parameters'] = node['parameters']
        for k in ('retryOnFail', 'maxTries', 'waitBetweenTries', 'onError', 'credentials'):
            if k in node: old[k] = node[k]
    else:
        d['nodes'].append(node); nodes[node['name']] = node

tpl = nodes['Claude Same-Event Check']
confirm = {
    'parameters': dict(tpl['parameters'], jsonBody="={{ JSON.stringify({model: $('Config').first().json.anthropicModel, max_tokens: 300, temperature: 0, messages:[{role:'user', content: $json.prompt}]}) }}"),
    'id': 'claude-same-event-confirm', 'name': 'Claude Same-Event Confirm', 'type': tpl['type'], 'typeVersion': tpl['typeVersion'],
    'position': [1870, 220], 'credentials': tpl['credentials'],
    # An API error leaves no text -> unreadable confirm -> Drop Same-Event Repeats stops the run.
    'retryOnFail': True, 'maxTries': 3, 'waitBetweenTries': 5000, 'onError': 'continueRegularOutput',
}
put(code_node('Same-Event Verify', with_lib(verify), [1760, 220], 'same-event-verify'))
put(confirm)
put(code_node('Drop Same-Event Repeats', with_lib(drop), nodes['Drop Same-Event Repeats']['position'], nodes['Drop Same-Event Repeats']['id']))

def link(a, b):
    conn[a] = {'main': [[{'node': b, 'type': 'main', 'index': 0}]]}
link('Pick Slot Story', 'Claude Same-Event Check')
link('Claude Same-Event Check', 'Same-Event Verify')
link('Same-Event Verify', 'Claude Same-Event Confirm')
link('Claude Same-Event Confirm', 'Drop Same-Event Repeats')
assert [t['node'] for t in conn['Drop Same-Event Repeats']['main'][0]] == ['Fetch Articles']

open(WF, 'w').write(json.dumps(d, indent=2, ensure_ascii=True) + '\n')
print('synced same-event check,', len(d['nodes']), 'nodes')
