#!/usr/bin/env python3
"""Adds/updates the source fact-check nodes in automation/n8n/AIFeed_Autopilot.json (the n8n fallback).

The shared code is copied from automation/actions/lib/factcheck.js (everything above
"// ---- end of shared source-check code ----") and articleText() from lib/articles.js,
so the fallback and GitHub Actions run the same checks. Idempotent: run it again after
editing those files. test/n8n-sync.test.js fails if the JSON drifts from the library.
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WF = os.path.join(ROOT, 'n8n', 'AIFeed_Autopilot.json')
FC = open(os.path.join(ROOT, 'actions', 'lib', 'factcheck.js')).read()
LIB = FC[:FC.index('// ---- end of shared source-check code ----')].rstrip() + '\n'
ART = open(os.path.join(ROOT, 'actions', 'lib', 'articles.js')).read()
m = re.search(r'(// Article body for captions[\s\S]*?\nfunction articleText\(html\) \{[\s\S]*?\n\}\n)', ART)
ARTICLE_TEXT = m.group(1)
SCHEDULE_NAME = 'Schedule 8:50am+5:50pm ET'

d = json.load(open(WF))
nodes = {n['name']: n for n in d['nodes']}
conn = d['connections']
EMPTY = "Reply with exactly: []"

def claude_node(name, prompt_expr, pos, max_tokens=4000):
    tpl = nodes['Claude Fix Accuracy']
    return {
        'parameters': dict(tpl['parameters'], jsonBody="={{ JSON.stringify({model: $('Config').first().json.anthropicModel, max_tokens: %d, temperature: 0, messages:[{role:'user', content: %s}]}) }}" % (max_tokens, prompt_expr)),
        'id': 'src-' + re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-'),
        'name': name, 'type': tpl['type'], 'typeVersion': tpl['typeVersion'], 'position': pos,
        'credentials': tpl['credentials'],
        'retryOnFail': True, 'maxTries': 3, 'waitBetweenTries': 5000, 'onError': 'continueRegularOutput',
    }

def code_node(name, code, pos):
    return {'parameters': {'jsCode': code}, 'id': 'src-' + re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-'),
            'name': name, 'type': 'n8n-nodes-base.code', 'typeVersion': 2, 'position': pos}

PARSE_GEN = r"""const capTxt = $('Claude Captions + Fact Check').first().json?.content?.[0]?.text || '';
let gen = [];
try { gen = JSON.parse((String(capTxt).replace(/```json|```/g, '').match(/\[[\s\S]*\]/) || ['[]'])[0]); }
catch (e) { throw new Error('Caption JSON parse failed: ' + capTxt.slice(0, 200)); }
"""
HDR = '// Source fact check (generated by automation/n8n/sync_source_check.py from automation/actions/lib/factcheck.js).\n'

prep = HDR + LIB + r"""
// One item per eligible candidate -> "Claude Source Check" runs once per candidate.
const { usable } = $('Fetch Articles').first().json;
""" + PARSE_GEN + r"""const out = gen.filter(g => usable[g.candidate] && g.supported && g.safe)
  .map(g => ({ json: { key: g.candidate, prompt: buildFactPrompt(usable[g.candidate], g, { allowRewrite: true }) } }));
return out.length ? out : [{ json: { key: null, prompt: '""" + EMPTY + r"""' } }];"""

apply1 = HDR + LIB + r"""
// Applies verdicts: unsupported body sentences dropped (or rewritten if the caption would get too thin),
// headline/summary/hook rewritten once; unreadable verdicts fail the candidate (supported=false -> next story).
const { usable } = $('Fetch Articles').first().json;
""" + PARSE_GEN + r"""const prep = $('Source Check Prep').all();
const res = $input.all();
const log = [];
const recheck = [];
prep.forEach((p, i) => {
  const key = p.json.key;
  if (key === null || key === undefined) return;
  const g = gen.find(x => x.candidate === key);
  if (!g) return;
  const r = applyFactVerdicts(g, res[i]?.json?.content?.[0]?.text || '', { allowRewrite: true });
  log.push({ candidate: key, title: usable[key].title, status: r.status, changes: r.changes, problems: r.problems });
  if (r.status === 'patched' && r.rewritten.length) {
    recheck.push({ key, only: r.rewritten, prompt: buildFactPrompt(usable[key], g, { allowRewrite: false, only: r.rewritten }) });
  }
});
const base = { gen, sourceCheckLog: log };
return recheck.length ? recheck.map(r => ({ json: Object.assign({}, r, base) })) : [{ json: Object.assign({ key: null, prompt: '""" + EMPTY + r"""' }, base) }];"""

apply2 = HDR + LIB + r"""
// Verifies the rewritten sentences once more; still unsupported or unreadable -> candidate fails.
const prev = $('Source Check Apply').all();
const res = $input.all();
const gen = JSON.parse(JSON.stringify(prev[0].json.gen || []));
const log = JSON.parse(JSON.stringify(prev[0].json.sourceCheckLog || []));
prev.forEach((p, i) => {
  const key = p.json.key;
  if (key === null || key === undefined) return;
  const g = gen.find(x => x.candidate === key);
  if (!g) return;
  const r = applyFactVerdicts(g, res[i]?.json?.content?.[0]?.text || '', { allowRewrite: false, only: p.json.only });
  if (r.status === 'fail') { const l = log.find(x => x.candidate === key); if (l) { l.status = 'fail'; l.problems = r.problems; } }
});
return [{ json: { gen, sourceCheckLog: log } }];"""

acc_prep = HDR + LIB + r"""
// Applies the one-time accuracy (hedge/$) fix to the source-checked copy, then sends it for a verify-only check.
const { usable } = $('Fetch Articles').first().json;
const gen = JSON.parse(JSON.stringify($('Source Recheck Apply').first().json.gen || []));
const prev = $('Accuracy Fix Needed?').first().json;
const ft = $('Claude Fix Accuracy').first().json?.content?.[0]?.text || '';
let fixNote = null, key = null;
try {
  const fix = JSON.parse((ft.replace(/```json|```/g, '').match(/\{[\s\S]*\}/) || ['{}'])[0]);
  const i = gen.findIndex(x => x.candidate === prev.accuracyCandidate);
  if (i >= 0 && fix && fix.graphicHeadline) { gen[i] = { ...gen[i], ...fix, candidate: prev.accuracyCandidate }; fixNote = 'accuracy regenerated for candidate ' + prev.accuracyCandidate; key = prev.accuracyCandidate; }
  else fixNote = 'accuracy regeneration unusable - falling back';
} catch (e) { fixNote = 'accuracy regeneration unparseable - falling back'; }
const g = key === null ? null : gen.find(x => x.candidate === key);
return [{ json: { key, gen, fixNote, prompt: g ? buildFactPrompt(usable[key], g, { allowRewrite: false }) : '""" + EMPTY + r"""' } }];"""

acc_apply = HDR + LIB + r"""
const p = $('Accuracy Recheck Prep').first().json;
const gen = JSON.parse(JSON.stringify(p.gen || []));
let fixNote = p.fixNote;
if (p.key !== null && p.key !== undefined) {
  const g = gen.find(x => x.candidate === p.key);
  const r = applyFactVerdicts(g, $input.first().json?.content?.[0]?.text || '', { allowRewrite: false });
  fixNote += ' | source check ' + r.status + (r.problems.length ? ': ' + r.problems.join('; ').slice(0, 300) : '');
}
return [{ json: { gen, fixNote } }];"""

li_prep = HDR + LIB + r"""
// The LinkedIn expansion is published as the website body: verify it against the source (no rewrite).
const q = $('Quality Checks + Build HTML').first().json;
const t = $input.first().json?.content?.[0]?.text || '';
let p = null;
try { p = JSON.parse((t.match(/\{[\s\S]*\}/) || ['{}'])[0]); } catch (e) { p = null; }
const ok = !!(p && Array.isArray(p.liParagraphs));
const g = ok ? { ...q.gen, liHook: p.liHook || q.gen.liHook, liParagraphs: p.liParagraphs, liTakeaway: p.liTakeaway || q.gen.liTakeaway } : null;
return [{ json: { ok, p, expandText: t, prompt: ok ? buildFactPrompt(q.story, g, { allowRewrite: false, scope: 'li' }) : '""" + EMPTY + r"""' } }];"""

def put(node):
    if node['name'] in nodes:
        old = nodes[node['name']]
        old['parameters'] = node['parameters']
        for k in ('retryOnFail', 'maxTries', 'waitBetweenTries', 'onError', 'credentials'):
            if k in node: old[k] = node[k]
    else:
        d['nodes'].append(node); nodes[node['name']] = node

q_pos = nodes['Quality Checks + Build HTML']['position']
put(code_node('Source Check Prep', prep, [2420, 220]))
put(claude_node('Claude Source Check', '$json.prompt', [2530, 380]))
put(code_node('Source Check Apply', apply1, [2640, 220]))
put(claude_node('Claude Source Recheck', '$json.prompt', [2750, 380]))
put(code_node('Source Recheck Apply', apply2, [2860, 220]))
put(code_node('Accuracy Recheck Prep', acc_prep, [2970, -650]))
put(claude_node('Claude Accuracy Recheck', '$json.prompt', [3190, -650]))
put(code_node('Accuracy Recheck Apply', acc_apply, [3410, -650]))
put(code_node('LI Expansion Check Prep', li_prep, [3080, -100]))
put(claude_node('Claude LI Expansion Check', '$json.prompt', [3190, -100]))

def link(a, b):
    conn[a] = {'main': [[{'node': b, 'type': 'main', 'index': 0}]]}
link('Claude Captions + Fact Check', 'Source Check Prep')
link('Source Check Prep', 'Claude Source Check')
link('Claude Source Check', 'Source Check Apply')
link('Source Check Apply', 'Claude Source Recheck')
link('Claude Source Recheck', 'Source Recheck Apply')
link('Source Recheck Apply', 'Quality Checks + Build HTML')
link('Claude Fix Accuracy', 'Accuracy Recheck Prep')
link('Accuracy Recheck Prep', 'Claude Accuracy Recheck')
link('Claude Accuracy Recheck', 'Accuracy Recheck Apply')
link('Accuracy Recheck Apply', 'Quality Checks + Build HTML')
link('Claude Expand LinkedIn', 'LI Expansion Check Prep')
link('LI Expansion Check Prep', 'Claude LI Expansion Check')
link('Claude LI Expansion Check', 'Merge LI Caption')

# Quality node: take caption parts from the source check (2nd run: accuracy fix + its check).
qn = nodes['Quality Checks + Build HTML']['parameters']
qc = qn['jsCode']
start = qc.index("const txt = $('Claude Captions + Fact Check')") if "const txt = $('Claude Captions + Fact Check')" in qc else qc.index('// SOURCE-CHECKED GEN')
end = qc.index('const words = s =>')
qc = qc[:start] + r"""// SOURCE-CHECKED GEN: caption parts after "Source Recheck Apply" (2nd run: after the accuracy fix and its source check).
const fixPass = $runIndex > 0; // 2nd run of this node = after the one-time accuracy regeneration (never loops again)
let gen = JSON.parse(JSON.stringify($(fixPass ? 'Accuracy Recheck Apply' : 'Source Recheck Apply').first().json.gen || []));
const fixNote = fixPass ? ($('Accuracy Recheck Apply').first().json.fixNote || null) : null;
""" + qc[end:]
if 'sourceCheck: $(' not in qc:
    qc = qc.replace("accuracyNote: fixNote, story: c,", "accuracyNote: fixNote, sourceCheck: $('Source Recheck Apply').first().json.sourceCheckLog || [], story: c,")
assert 'sourceCheck: $(' in qc
qn['jsCode'] = qc

# Merge LI Caption: drop an expansion that failed the source check.
mn = nodes['Merge LI Caption']['parameters']
mc = mn['jsCode']
if '// SOURCE CHECK LIB' in mc:
    mc = mc[:mc.index('// SOURCE CHECK LIB')] + mc[mc.index('// END SOURCE CHECK LIB\n') + len('// END SOURCE CHECK LIB\n'):]
anchor = "const q = $('Quality Checks + Build HTML').first();"
mc = mc.replace(anchor, '// SOURCE CHECK LIB\n' + LIB + '// END SOURCE CHECK LIB\n' + anchor, 1)
old_t = "const t = ($input.first().json?.content?.[0]?.text || '');"
new_t = r"""const lp = $('LI Expansion Check Prep').first().json;
let t = lp.expandText || '';
let liFactNote = null;
if (lp.ok) {
  const g2 = { ...q.json.gen, liHook: lp.p.liHook || q.json.gen.liHook, liParagraphs: lp.p.liParagraphs, liTakeaway: lp.p.liTakeaway || q.json.gen.liTakeaway };
  const r = applyFactVerdicts(g2, $input.first().json?.content?.[0]?.text || '', { allowRewrite: false, scope: 'li' });
  if (r.status !== 'pass') { t = ''; liFactNote = 'LinkedIn expansion failed source check - kept original'; }
}"""
if old_t in mc: mc = mc.replace(old_t, new_t)
mc = mc.replace("return [{ json: { liCaption, liWarning }, binary: q.binary }];", "if (liFactNote) liWarning = liFactNote;\nreturn [{ json: { liCaption, liWarning }, binary: q.binary }];") if 'if (liFactNote) liWarning' not in mc else mc
mn['jsCode'] = mc

# Fetch Articles: same article-body extraction as Actions.
fa = nodes['Fetch Articles']['parameters']
fc = fa['jsCode']
if '// Article body for captions' in fc:
    fc = re.sub(r'// Article body for captions[\s\S]*?\nfunction articleText\(html\) \{[\s\S]*?\n\}\n', lambda _m: ARTICLE_TEXT, fc, count=1)
else:
    fc = fc.replace("const { candidates, history } = $input.first().json;", ARTICLE_TEXT + "const { candidates, history } = $input.first().json;", 1)
fc = fc.replace("const text = html.replace(/<script[\\s\\S]*?<\\/script>|<style[\\s\\S]*?<\\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').slice(0, 3500);", "const text = articleText(html);")
assert 'const text = articleText(html);' in fc
fa['jsCode'] = fc

# Claim Check: a dry run previews even when the slot is taken (it never claims or posts).
cc = nodes['Claim Check']['parameters']
cj = cc['jsCode']
if 'cfg.dryRun' not in cj:
    cj = cj.replace("const blocked = status === 'claimed' || status === 'posted' || !!posted;",
                    "const wouldBlock = status === 'claimed' || status === 'posted' || !!posted;\nconst blocked = wouldBlock && !cfg.dryRun; // dry run previews only")
    cj = cj.replace("return [{ json: { blocked, reason,", "return [{ json: { blocked, reason: (wouldBlock && cfg.dryRun ? 'DRY RUN (a real run would skip): ' : '') + reason,")
cj = cj.replace(": blocked ? ('slot ' + key + ' is '", ": wouldBlock ? ('slot ' + key + ' is '")
cj = cj.replace('8:40/5:40', '8:50/5:50')
cc['jsCode'] = cj

# Dry run output shows the source-check result per candidate.
dc = nodes['Dry: Collect']['parameters']
if 'sourceCheck: q.sourceCheck' not in dc['jsCode']:
    dc['jsCode'] = dc['jsCode'].replace('failures: q.failures }', 'failures: q.failures, sourceCheck: q.sourceCheck, accuracyNote: q.accuracyNote }')
assert 'sourceCheck: q.sourceCheck' in dc['jsCode']

# Schedule 8:50 / 17:50 ET.
for old_name in [n['name'] for n in d['nodes'] if n['type'].endswith('scheduleTrigger')]:
    n = nodes[old_name]
    n['parameters']['rule'] = {'interval': [{'field': 'cronExpression', 'expression': '50 8,17 * * *'}]}
    if old_name != SCHEDULE_NAME:
        n['name'] = SCHEDULE_NAME
        conn[SCHEDULE_NAME] = conn.pop(old_name)
d['name'] = 'AIFeed Autopilot (fallback 8:50am / 5:50pm ET)'

open(WF, 'w').write(json.dumps(d, indent=2, ensure_ascii=True) + '\n')
print('synced', len(d['nodes']), 'nodes')
